OtoGaleri/Models/Araclar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        public int Id { get; set; }
        public string A_Marka { get; set; }
        public string A_Plaka { get; set; }
        public Nullable<int> M_Id { get; set; }
    }
}

OtoGaleri/Controllers/AraclarController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using FluentValidation.Results;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OtoGaleri.Controllers
{
    public class AraclarController : Controller
    {
        // GET: Musteriler
        AracManager arm = new AracManager(new EfAraclarDal());
        AracValidator aracValidator = new AracValidator();

        public ActionResult Index()
        {
            var Aracvalues = arm.GetList();
            return View(Aracvalues);
        }
        [HttpGet]
        public ActionResult AddArac()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddArac(Araclar p)
        {
            ValidationResult results = aracValidator.Validate(p);
            if (results.IsValid)
            {
                arm.AracAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            return View();
        }
        [HttpGet]
        public ActionResult EditArac(int id)
        {
            List<SelectListItem> valuecategory = (from x in arm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.A_Marka,
                                                      Value = x.Id.ToString()
                                                  }).ToList();
            ViewBag.vlc = valuecategory;
            var aracValue = arm.GetByID(id);
            return View();
        }
        [HttpPost]
        public ActionResult EditArac(Araclar p)
        {
            arm.AracUpdate(p);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteArac(int id)
        {
            var aracValue = arm.GetByID(id);
            arm.AracDelete(aracValue);
            return RedirectToAction("Index");

        }
    }
}

OtoGaleri/Views/Araclar/AddArac.cshtml
@model EntityLayer.Concrete.Araclar

@{
    ViewBag.Title = "AddArac";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Araç Ekleme</h1>
<br />
@using (Html.BeginForm("AddArac", "Araclar", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Araç Markası")
        @Html.TextBoxFor(x => x.A_Marka, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.A_Marka)
        <br />
        @Html.Label("Araç Plaka")
        @Html.TextBoxFor(x => x.A_Plaka, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.A_Plaka)
        <br />
        @Html.Label("Araç Sahibi")
        @Html.TextBoxFor(x => x.M_Id, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_Id)
        <br />
        <button class="btn btn-info">Araç Ekle</button>
    </div>

}

OtoGaleri/Views/Araclar/EditArac.cshtml
@model EntityLayer.Concrete.Araclar

@{
    ViewBag.Title = "EditArac";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Araç Düzenleme Sayfası</h2>
@using (Html.BeginForm("EditArac", "Araclar", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Araç Id")
        @Html.TextBoxFor(x => x.Id, new { @class = "form-control" })
        <br />
        @Html.Label("Araç Marka")
        @Html.TextBoxFor(x => x.A_Marka, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.A_Marka)
        <br />
        @Html.Label("Araç Plaka")
        @Html.TextBoxFor(x => x.A_Plaka, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.A_Plaka)
        <br />
        @Html.Label("Araç Sahibi")
        @Html.TextBoxFor(x => x.M_Id, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_Id)
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

OtoGaleri/Views/Araclar/Index.cshtml
@using EntityLayer.Concrete
@model List<Araclar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Araçlar</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Araç İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Araç Marka
                            </th>
                            <th style="width: 30%">
                                Araç Plaka
                            </th>
                            <th style="width: 20%">
                                Müşteri No
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                
                                <td>
                                    @item.A_Marka
                                </td>
                                
                                <td>
                                    @item.A_Plaka
                                </td>
                                
                                <td>
                                    @item.M_Id
                                </td>

                                <td class="project-actions text-right">
                                    <a class="btn btn-info btn-sm" href="/Araclar/EditArac/@item.Id">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Güncelle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Araclar/DeleteArac/@item.Id">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>
<a href="/Araclar/AddArac/" class="btn btn-primary">Yeni Araç Girişi</a>