OtoGaleri/Models/Musteriler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int Id { get; set; }
        public string M_Name { get; set; }
        public string M_Surname { get; set; }
    }
}

OtoGaleri/Controllers/MusterilerController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OtoGaleri.Controllers
{
    public class MusterilerController : Controller
    {
        // GET: Musteriler
        MusteriManager mm = new MusteriManager(new EfMusterilerDal());
        MusteriValidator musteriValidator = new MusteriValidator();

        public ActionResult Index()
        {
            var Musterivalues = mm.GetList();
            return View(Musterivalues);
        }
        [HttpGet]
        public ActionResult AddMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddMusteri(Musteriler p)
        {
            ValidationResult results = musteriValidator.Validate(p);
            if (results.IsValid)
            {
                mm.MusteriAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage); 
                }
            }
            
            return View();
        }
        [HttpGet]
        public ActionResult EditMusteri(int id)
        {
            var musterivalue = mm.GetByID(id);
            return View(musterivalue);
        }
        [HttpPost]
        public ActionResult EditMusteri(Musteriler p)
        {
            ValidationResult results = musteriValidator.Validate(p);
            if (results.IsValid)
            {
                mm.MusteriUpdate(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult DeleteMusteri(int id)
        {
            var musteriValue = mm.GetByID(id);
            mm.MusteriDelete(musteriValue);
            return RedirectToAction("Index");

        }
    }
}

OtoGaleri/Views/Musteriler/AddMusteri.cshtml
@model EntityLayer.Concrete.Musteriler
@{
    ViewBag.Title = "AddMusteri";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Müşteri Ekleme</h1>
<br />
@using (Html.BeginForm("AddMusteri", "Musteriler", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Müşteri Adı")
        @Html.TextBoxFor(x => x.M_Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_Name)
        <br />
        @Html.Label("Müşteri Soyadı")
        @Html.TextBoxFor(x => x.M_Surname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_Surname)
        <br />
        @Html.Label("Müşteri Hakkında")
        @Html.TextBoxFor(x => x.M_About, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_About)
        <br />
        @Html.Label("Müşteri Unvan")
        @Html.TextBoxFor(x => x.M_Unvan, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_Unvan)
        <br />
        <button class="btn btn-info">Müşteri Ekle</button>
    </div>

}

OtoGaleri/Views/Musteriler/EditMusteri.cshtml
@model EntityLayer.Concrete.Musteriler
@{
    ViewBag.Title = "EditMusteri";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Müşteri Düzenleme Sayfası</h2>
@using (Html.BeginForm("EditMusteri", "Musteriler", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Müşteri Id")
        @Html.TextBoxFor(x => x.Id, new { @class = "form-control" })
        <br />
        @Html.Label("Müşteri Adı")
        @Html.TextBoxFor(x => x.M_Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_Name)
        <br />
        @Html.Label("Müşteri Soyadı")
        @Html.TextBoxFor(x => x.M_Surname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_Surname)
        <br />
        @Html.Label("Müşteri Hakkında")
        @Html.TextBoxFor(x => x.M_About, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_About)
        <br />
        @Html.Label("Müşteri Unvan")
        @Html.TextBoxFor(x => x.M_Unvan, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_Unvan)
        <button class="btn btn-success">Güncelle</button>
    </div>
}

OtoGaleri/Views/Musteriler/GetMusteriList.cshtml
@using EntityLayer.Concrete
@{
    ViewBag.Title = "GetMusteriList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Müşteri Adı</th>
        <th>Müşteri Soyadı</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.M_Name</td>
            <td>@item.M_Surname</td>
        </tr>
    }
</table>
<br />
<a href="/Musteriler/AddMusteri" class="btn btn-info">Yeni Müşteri Ekle</a>
<br /><br />
<a href="/Musteriler/Index" class="btn btn-info">Yeni Müşteri Ekle</a>

OtoGaleri/Views/Musteriler/Index.cshtml
@using EntityLayer.Concrete
@model List<Musteriler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- /.navbar -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Müşteriler</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-header text-muted border-bottom-0">
                                    @item.M_Unvan
                                </div>
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@item.M_Name @item.M_Surname</b></h2>
                                            <p class="text-muted text-sm"><b>Hakkında: </b>@item.M_About.</p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img src="~/AdminLTE-3.0.4/dist/img/user1-128x128.jpg" alt="" class="img-circle img-fluid">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-bold; text-left">
                                        <a href="/Musteriler/DeleteMusteri/@item.Id" class="btn btn-sm bg-teal">
                                            <i class="fas fa-remove">Sil</i>
                                        </a>
                                        <a href="/Musteriler/EditMusteri/@item.Id" class="btn btn-sm btn-primary">
                                            <i class="fas fa-user"></i> Profili Düzenle
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
</body>
</html>
<a href="/Musteriler/AddMusteri/" class="btn btn-primary">Müşteri Ekle</a>