OtoGaleri/Models/Adminler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminler
    {
        public int Id { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_Surname { get; set; }
    }
}

OtoGaleri/Controllers/AdminlerController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace OtoGaleri.Controllers
{
    public class AdminlerController : Controller
    {
        // GET: Musteriler
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Adminler p)
        {
            Context c = new Context();
            var adminuserinfo=c.Adminlers.FirstOrDefault(x=>x.Admin_Name==p.Admin_Name && 
            x.Admin_Surname==p.Admin_Surname);
            if (adminuserinfo!=null)
            {
                FormsAuthentication.SetAuthCookie(adminuserinfo.Admin_Name, false);
                Session["Admin_Name"] = adminuserinfo.Admin_Name;
                return RedirectToAction("Index", "AdminKullanici");
            }
            else
            {
                return RedirectToAction("Index");
            }
            
        }



    }
}

OtoGaleri/Views/Adminler/AddAdmin.cshtml
@model EntityLayer.Concrete.Adminler
@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Admin Ekleme</h1>
<br />
@using (Html.BeginForm("AddAdmin", "Adminler", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Admin Adı")
        @Html.TextBoxFor(x => x.Admin_Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Admin_Name)
        <br />
        @Html.Label("Admin Soyadı")
        @Html.TextBoxFor(x => x.Admin_Surname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Admin_Surname)
        @*<br />
        @Html.Label("Müşteri Hakkında")
        @Html.TextBoxFor(x => x.M_About, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_About)
        <br />
        @Html.Label("Müşteri Unvan")
        @Html.TextBoxFor(x => x.M_Unvan, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.M_Unvan)*@
        <br />
        <button class="btn btn-info">Admin Ekle</button>
    </div>

}

OtoGaleri/Views/Adminler/EditAdmin.cshtml
@model EntityLayer.Concrete.Adminler

@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Admin Düzenleme Sayfası</h2>
@using (Html.BeginForm("EditAdmin", "Adminler", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Admin Id")
        @Html.TextBoxFor(x => x.Id, new { @class = "form-control" })
        <br />
        @Html.Label("Admin Adı")
        @Html.TextBoxFor(x => x.Admin_Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Admin_Name)
        <br />
        @Html.Label("Admin Soyadı")
        @Html.TextBoxFor(x => x.Admin_Surname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Admin_Surname)
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

OtoGaleri/Views/Adminler/Index.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <title>Sakaoğlu Rent a Car</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/login-form-19/css/style.css">

</head>
<body>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Sakaoğlu Rent a Car</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap py-5">
                        <div class="img d-flex align-items-center justify-content-center" style="background-image: url(/AdminLTE-3.0.4/login-form-19/images/bg.jpg);"></div>
                        <h3 class="text-center mb-0">Hoşgeldiniz</h3>
                        <p class="text-center">Lütfen bilgilerinizi giriniz.</p>
                        @using (Html.BeginForm("Index", "Adminler", FormMethod.Post))
                        {
                            <div class="form-group">
                                <div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-user"></span></div>
                                <input type="text" class="form-control" name="Admin_Name" placeholder="Kullanıcı Adı" required>
                            </div>
                            <div class="form-group">
                                <div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-lock"></span></div>
                                <input type="password" class="form-control" name="Admin_Surname" placeholder="Kullanıcı Soyadı" required>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-100 text-md-right">
                                    <a href="#">Forgot Password</a>
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn form-control btn-primary rounded submit px-3">Giriş Yap</button>
                            </div>
                        }
                        <div class="w-100 text-center mt-4 text">
                            <a href="/Home/HomePage/">Anasayfaya Dön</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/AdminLTE-3.0.4/login-form-19/js/jquery.min.js"></script>
    <script src="~/AdminLTE-3.0.4/login-form-19/js/popper.js"></script>
    <script src="~/AdminLTE-3.0.4/login-form-19/js/bootstrap.min.js"></script>
    <script src="~/AdminLTE-3.0.4/login-form-19/js/main.js"></script>

</body>
</html>

OtoGaleri/Views/Adminler/Login.cshtml
@using EntityLayer.Concrete
@model List<Adminler>
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!doctype html>
<html lang="en">
<head>
    <title>Sakaoğlu Rent a Car</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/login-form-19/css/style.css">

</head>
<body>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Sakaoğlu Rent a Car</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap py-5">
                        <div class="img d-flex align-items-center justify-content-center" style="background-image: url(/AdminLTE-3.0.4/login-form-19/images/bg.jpg);"></div>
                        <h3 class="text-center mb-0">Hoşgeldiniz</h3>
                        <p class="text-center">Lütfen bilgilerinizi giriniz.</p>
                        @using (Html.BeginForm("Login", "Adminler", FormMethod.Post))
                        {
                            <div class="form-group">
                                <div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-user"></span></div>
                                <input type="text" class="form-control" name="Admin_Name" placeholder="Kullanıcı Adı" required>
                            </div>
                            <div class="form-group">
                                <div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-lock"></span></div>
                                <input type="password" class="form-control" name="Admin_Surname" placeholder="Kullanıcı Soyadı" required>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-100 text-md-right">
                                    <a href="#">Forgot Password</a>
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn form-control btn-primary rounded submit px-3">Giriş Yap</button>
                            </div>
                        }
                        <div class="w-100 text-center mt-4 text">
                            <a href="#">Anasayfaya Dön</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/AdminLTE-3.0.4/login-form-19/js/jquery.min.js"></script>
    <script src="~/AdminLTE-3.0.4/login-form-19/js/popper.js"></script>
    <script src="~/AdminLTE-3.0.4/login-form-19/js/bootstrap.min.js"></script>
    <script src="~/AdminLTE-3.0.4/login-form-19/js/main.js"></script>

</body>
</html>