OtoGaleri/Controllers/AdminKullaniciController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OtoGaleri.Controllers
{
    public class AdminKullaniciController : Controller
    {
        // GET: AdminKullanici
        KullaniciManager km = new KullaniciManager(new EfKullanicilarDal());
        [Authorize]

        public ActionResult Index()
        {
            var kullanicivalues = km.GetList();
            return View(kullanicivalues);
        }
        [HttpGet]
        public ActionResult AddKullanici()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddKullanici(Kullanicilar p)
        {
            KullaniciValidator kullaniciValidator = new KullaniciValidator();
            ValidationResult results = kullaniciValidator.Validate(p);
            if (results.IsValid)
            {
                km.KullaniciAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult DeleteKullanici(int id)
        {
            var kullanicivalue = km.GetByID(id);
            km.KullaniciDelete(kullanicivalue);
            return RedirectToAction("Index");
            
        }
        [HttpGet]
        public ActionResult EditKullanicilar(int id)
        {
            var kullaniciValue = km.GetByID(id);
            return View(kullaniciValue);

        }

        [HttpPost]
        public ActionResult EditKullanicilar(Kullanicilar p)
        {
            km.KullaniciUpdate(p);
            return RedirectToAction("Index");

        }
    }
}

OtoGaleri/Views/AdminKullanici/AddKullanici.cshtml
@model EntityLayer.Concrete.Kullanicilar
@{
    ViewBag.Title = "AddKullanici";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Kullanıcı Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddKullanici", "AdminKullanici", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kullanıcı Adı")
        @Html.TextBoxFor(x => x.K_Adi, new {@class="form-control"})
        @Html.ValidationMessageFor(x => x.K_Adi)
        <br /> <br />
        @Html.Label("Parola")
        @Html.TextBoxFor(x => x.K_Sifre, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.K_Sifre)
        <br /> <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

OtoGaleri/Views/AdminKullanici/EditKullanicilar.cshtml
@model EntityLayer.Concrete.Kullanicilar
@{
    ViewBag.Title = "EditKullanicilar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Kullanıcı Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditKullanicilar", "AdminKullanici", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kullanıcı ID")
        @Html.TextBoxFor(x => x.Id, new { @class = "form-control" })
        <br />
        @Html.Label("Kullanıcı Adı")
        @Html.TextBoxFor(x => x.K_Adi, new { @class = "form-control" })
        <br /> <br />
        <button class="btn btn-info">Güncelle</button>

    </div>
}

OtoGaleri/Views/AdminKullanici/Index.cshtml
@using EntityLayer.Concrete
@model List<Kullanicilar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kullanıcı Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.Id</th>
            <td>@item.K_Adi</td>
            <td><a href="/AdminKullanici/DeleteKullanici/@item.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminKullanici/EditKullanicilar/@item.Id" class="btn btn-warning">Güncelle</a></td>
            


        </tr>
    }
</table>
<a href="/AdminKullanici/AddKullanici" class="btn btn-info">Yeni Kullanıcı Ekle</a>  